include:
- project: uniget-org/templates
  file: uniget.yaml
  ref: main

docker-desktop:
  extends:
  - .uniget-install
  variables:
    uniget_prefix: helper
    uniget_tools: gojq release-cli
  image: registry.gitlab.com/uniget-org/images/ubuntu:rolling
  script:
  - |
    VERSION="$(
        curl --silent --show-error --location --fail "https://github.com/docker/docs/raw/main/content/manuals/desktop/release-notes.md" \
        | grep '{{< desktop-install all=true' \
        | head -n 1 \
        | sed -E 's/^.+version="([^"]+)".+$/\1/'
    )"
    if test -z "${VERSION}"; then
        echo "Failed to fetch latest tag and extract version from GitHub"
        exit 1
    fi
    echo "Got version <${VERSION}>"
  release:
    ref: $CI_COMMIT_SHA
    tag_name: docker-desktop/${VERSION}
    name: docker-desktop v${VERSION}
    description: "Custom release of docker-desktop v${VERSION}"
