name: k3s

on:
  schedule:
  - cron: "47 3 * * *"
  push:
    branches:
    - main
    paths:
    - .github/workflows/k3s.yml
  workflow_dispatch:

concurrency:
  group: k3s

jobs:

  fetch:
    name: Fetch
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Fetch
      id: fetch
      run: |
        VERSION="$(
            curl --silent --show-error --location --fail \
                --url "https://api.github.com/repos/k3s-io/k3s/releases/latest" \
            | jq --raw-output '.tag_name' \
            | sed -E 's/^v([[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+)\+k3s([[:digit:]]+)$/\1.\2/'
        )"
        if test -z "${VERSION}"; then
            echo "Failed to fetch latest tag and extract version from GitHub"
            exit 1
        fi
        echo "Got version <${VERSION}>"

        echo "version=${VERSION}" >>${GITHUB_OUTPUT}

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.BOT_GITHUB_TOKEN }}
        allowUpdates: true
        name: "k3s v${{ steps.fetch.outputs.version }}"
        tag: k3s/${{ steps.fetch.outputs.version }}
        draft: false
        prerelease: false